### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by Kretikus** [garettbass/reflect#1]
Can you please tell me, under which licence you hhjave published this code?

**Comment by garettbass** [comment]
Thank you for your interest in this project.  I have added the MIT license.  I would be very interested to hear about any projects you undertake using this library.  Good luck.

**Comment by Kretikus** [comment]
Great, thank you!

We have a C++ component that is called by a Java backend via HTTPS and JSON. Currently, the server code is passing JSON-Objects around and the code is extracting the required fields "on-the-fly".
I would like to define structs in which the JSON-Data is deserialized at the earliest point possible and continue wirh these explicit structs instead of  generic JSON-Objects
This hat two advantages:
a) It documents the protocol
b) It identifies ill-formed JSON payloads early.

Does it make sense?
